# Generated by Django 6.0 on 2025-12-24
# Manual migration for normalized models (3NF)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_gamerating'),
        ('api_v1', '0013_alter_buyuser_id_alter_developer_id_alter_game_id_and_more'),
    ]

    operations = [
        # ===== CART MODEL (новая модель корзины) =====
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(default='buy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        
        # ===== ORDER STATUS (справочник статусов) =====
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(
                    choices=[
                        ('pending', 'Ожидает оплаты'),
                        ('paid', 'Оплачен'),
                        ('processing', 'В обработке'),
                        ('shipped', 'Отправлен'),
                        ('delivered', 'Доставлен'),
                        ('completed', 'Завершён'),
                        ('cancelled', 'Отменён'),
                        ('refunded', 'Возврат')
                    ],
                    max_length=20,
                    unique=True
                )),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
                'ordering': ['sort_order'],
            },
        ),
        
        # ===== PAYMENT METHOD (справочник способов оплаты) =====
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        
        # ===== ORDER (шапка заказа) =====
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(default='buy', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='orders',
                    to='web.orderstatus'
                )),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        
        # ===== ORDER ITEM (позиции заказа) =====
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_id', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='items',
                    to='web.order'
                )),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        
        # ===== PAYMENT (платёж) =====
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Ожидает'),
                        ('processing', 'Обрабатывается'),
                        ('completed', 'Завершён'),
                        ('failed', 'Ошибка'),
                        ('refunded', 'Возврат'),
                        ('cancelled', 'Отменён')
                    ],
                    default='pending',
                    max_length=20
                )),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('order', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='payment',
                    to='web.order'
                )),
                ('method', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='web.paymentmethod'
                )),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        
        # ===== SELLER PAYOUT (выплаты продавцам) =====
        migrations.CreateModel(
            name='SellerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Ожидает'),
                        ('processing', 'Обрабатывается'),
                        ('completed', 'Выплачено'),
                        ('failed', 'Ошибка')
                    ],
                    default='pending',
                    max_length=20
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='seller_payouts',
                    to='web.orderitem'
                )),
            ],
            options={
                'verbose_name': 'Выплата продавцу',
                'verbose_name_plural': 'Выплаты продавцам',
            },
        ),
        
        # ===== ОБНОВЛЕНИЯ СУЩЕСТВУЮЩИХ МОДЕЛЕЙ =====
        
        # Удаляем старый unique_together constraint из CartItem
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        
        # Добавляем поле cart к CartItem
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='web.cart'
            ),
        ),
        
        # Делаем user_id и user_type nullable в CartItem (для обратной совместимости)
        migrations.AlterField(
            model_name='cartitem',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        
        # Меняем quantity на PositiveIntegerField
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        
        # Добавляем Meta для SupportMessage
        migrations.AlterModelOptions(
            name='supportmessage',
            options={
                'ordering': ['timestamp'],
                'verbose_name': 'Сообщение поддержки',
                'verbose_name_plural': 'Сообщения поддержки'
            },
        ),
        
        # Добавляем Meta для GameRating
        migrations.AlterModelOptions(
            name='gamerating',
            options={
                'verbose_name': 'Рейтинг игры',
                'verbose_name_plural': 'Рейтинги игр'
            },
        ),
        
        # ===== CONSTRAINTS =====
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('user_id', 'user_type'),
                name='unique_active_cart_per_user'
            ),
        ),
    ]

