# Generated by Django 6.0 on 2025-12-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_cart_order_payment_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=10)),
                ('chat_key', models.CharField(max_length=255)),
                ('last_read_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Статус прочтения чата',
                'verbose_name_plural': 'Статусы прочтения чатов',
            },
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'game_id'), name='unique_game_in_cart'),
        ),
        migrations.AlterUniqueTogether(
            name='chatreadstatus',
            unique_together={('user_id', 'user_type', 'chat_key')},
        ),
    ]
