"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Построение путей внутри проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Настройки для быстрого старта - не подходят для продакшена
# Подробности: https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ПРЕДУПРЕЖДЕНИЕ БЕЗОПАСНОСТИ: держите секретный ключ в секрете в продакшене!
SECRET_KEY = 'django-insecure-v8esy-n46zgkzyt(+6!02=ty6771lkap&h1skdtz_rlg4$(@wf'

# ПРЕДУПРЕЖДЕНИЕ БЕЗОПАСНОСТИ: не включайте DEBUG в продакшене!
DEBUG = True

# Разрешенные хосты для доступа
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.0.105']

# Доверенные источники для CSRF
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]


# Определение приложений

INSTALLED_APPS = [
    'django.contrib.admin',  # Админка Django
    'django.contrib.auth',  # Аутентификация
    'django.contrib.contenttypes',  # Типы контента
    'django.contrib.sessions',  # Сессии
    'django.contrib.messages',  # Сообщения
    'django.contrib.staticfiles',  # Статические файлы
    'rest_framework',  # Django REST Framework
    'drf_spectacular',  # Документация API
    'api_v1',  # Наше API приложение
    'store',  # Приложение магазина
    'web'  # Web интерфейс
]

# Промежуточное ПО (middleware)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Безопасность
    'django.contrib.sessions.middleware.SessionMiddleware',  # Управление сессиями
    'django.middleware.common.CommonMiddleware',  # Общие функции
    'django.middleware.csrf.CsrfViewMiddleware',  # Защита CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Аутентификация
    'django.contrib.messages.middleware.MessageMiddleware',  # Сообщения
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Защита от clickjacking
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Настройки баз данных
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {  # Единая база данных для всех моделей
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
}

# Маршрутизаторы баз данных не нужны - используем одну БД
# DATABASE_ROUTERS = ['api_v1.routers.BuySellRouter']


# Валидация паролей
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # Проверка схожести с атрибутами пользователя
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # Минимальная длина
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # Общие пароли
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # Только цифры
    },
]

# Интернационализация
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'  # Код языка

TIME_ZONE = 'UTC'  # Часовой пояс

USE_I18N = True  # Включить интернационализацию

USE_TZ = True  # Использовать timezone

# Статические файлы (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'  # URL для статических файлов

# Медиа файлы (загруженные пользователем)
MEDIA_URL = '/media/'  # URL для медиа файлов
MEDIA_ROOT = BASE_DIR / 'media'  # Папка для хранения медиа файлов

# Настройки загрузки файлов
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # Максимальный размер файла в памяти (10MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # Максимальный размер данных (10MB)
FILE_UPLOAD_MAX_NUMBER_OF_FILES = 10  # Максимальное количество файлов

# Настройки REST Framework
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Схема для документации API
}

# Настройки сессий
SESSION_COOKIE_AGE = 2592000  # 30 дней
