# Generated by Django 4.2 on 2025-12-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='display_name',
            field=models.CharField(default='Гость', max_length=100),
        ),
    ]
