# Generated by Django 4.2 on 2025-12-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_delete_supportmessage_game_discount_price_game_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('shooter', 'Шутеры'), ('horror', 'Ужастики'), ('rpg', 'RPG'), ('strategy', 'Стратегии'), ('adventure', 'Приключения'), ('racing', 'Гонки'), ('sports', 'Спорт'), ('puzzle', 'Головоломки')], default='shooter', max_length=20),
        ),
    ]
