# Generated by Django 4.2 on 2025-12-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_alter_game_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
