# Generated by Django 4.2 on 2025-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_game_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selluser',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='selluser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='selluser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='selluser',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='selluser',
            name='website',
        ),
        migrations.AddField(
            model_name='selluser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selluser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selluser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='selluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
