# Generated by Django 4.2 on 2025-12-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_remove_selluser_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
