# Generated by Django 6.0 on 2025-12-24
# Modified to handle seller field conversion properly

import django.db.models.deletion
from django.db import migrations, models


def migrate_seller_to_fk(apps, schema_editor):
    """
    Миграция данных: конвертируем seller (username) в seller (FK)
    """
    Game = apps.get_model('api_v1', 'Game')
    SellUser = apps.get_model('api_v1', 'SellUser')
    
    db_alias = schema_editor.connection.alias
    
    for game in Game.objects.using(db_alias).all():
        if game.seller_username:
            try:
                seller = SellUser.objects.using(db_alias).get(username=game.seller_username)
                game.seller_id = seller.id
                game.save(using=db_alias)
            except SellUser.DoesNotExist:
                # Продавец не найден - оставляем seller_id = None
                game.seller_id = None
                game.save(using=db_alias)


def reverse_migrate_seller(apps, schema_editor):
    """
    Обратная миграция: конвертируем seller (FK) в seller_username
    """
    Game = apps.get_model('api_v1', 'Game')
    SellUser = apps.get_model('api_v1', 'SellUser')
    
    db_alias = schema_editor.connection.alias
    
    for game in Game.objects.using(db_alias).all():
        if game.seller_id:
            try:
                seller = SellUser.objects.using(db_alias).get(id=game.seller_id)
                game.seller_username = seller.username
                game.save(using=db_alias)
            except SellUser.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0013_alter_buyuser_id_alter_developer_id_alter_game_id_and_more'),
    ]

    operations = [
        # 1. Meta options
        migrations.AlterModelOptions(
            name='buyuser',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Разработчик', 'verbose_name_plural': 'Разработчики'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='selluser',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        
        # 2. Remove game_type
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        
        # 3. Add icon to genre
        migrations.AddField(
            model_name='genre',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        
        # 4. Rename old seller to seller_username (сохраняем старые данные)
        migrations.RenameField(
            model_name='game',
            old_name='seller',
            new_name='seller_username',
        ),
        
        # 5. Add new seller field as FK
        migrations.AddField(
            model_name='game',
            name='seller',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='games',
                to='api_v1.selluser'
            ),
        ),
        
        # 6. Data migration: конвертируем username в FK
        migrations.RunPython(
            migrate_seller_to_fk,
            reverse_migrate_seller
        ),
    ]
